create table if not exists problem_gt_candidate (
  id bigint primary key auto_increment,
  project_id bigint not null,
  source_run_key varchar(200) not null,
  candidate_id varchar(100) not null,
  candidate_key varchar(64) not null,
  note_no varchar(50),
  note_name varchar(300),
  folder varchar(300),
  source varchar(50),
  bucket varchar(100),
  risk varchar(50),
  recommended_action varchar(100),
  suggested_issue_type varchar(100),
  reason text,
  candidate_kind varchar(120),
  priority int,
  period_bucket varchar(100),
  table_path varchar(1000),
  section_path varchar(1000),
  row_label varchar(1000),
  column_label varchar(1000),
  period_label varchar(200),
  source_value text,
  target_value text,
  missing_cells varchar(1000),
  missing_values text,
  current_gt_overlap varchar(1000),
  current_final_hint text,
  manual_decision varchar(120),
  manual_rationale text,
  source_locator varchar(1000),
  target_locator varchar(1000),
  pdf_context mediumtext,
  raw_payload_json longtext,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_problem_gt_candidate_run_id (project_id, source_run_key, candidate_id),
  key idx_problem_gt_candidate_key (project_id, candidate_key),
  key idx_problem_gt_candidate_review (project_id, bucket, risk, note_no),
  key idx_problem_gt_candidate_run (project_id, source_run_key, updated_at, id),
  key idx_problem_gt_candidate_note (project_id, note_no, suggested_issue_type)
) engine=InnoDB default charset=utf8mb4;

create table if not exists problem_gt_decision (
  id bigint primary key auto_increment,
  project_id bigint not null,
  candidate_key varchar(64) not null,
  candidate_id varchar(100),
  decision varchar(80) not null,
  issue_type varchar(100),
  comment text,
  reviewer varchar(100),
  reviewed_at datetime not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_problem_gt_decision_key (project_id, candidate_key),
  key idx_problem_gt_decision_project (project_id, decision, updated_at),
  key idx_problem_gt_decision_candidate_id (project_id, candidate_id)
) engine=InnoDB default charset=utf8mb4;
